server:
  port: 2018
spring:
  application:
    name: apple
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.214.43:3306/lumia?useUnicode=true&characterEncoding=utf-8
    username: lumia
    password: lumia830
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
#file和path两者只能存其一
logging:
#  file: apple.log
  path: ${LOG_PATH:logs}
  level:
    com.spring.apple: info